(   ACTION
    , LIST_OF_MEETINGS
    , LOCATION
    , LOCATION_NAME
    , LOCATION_ADDED
    , WORKSPACE
    , WORKSPACE_ADDED
    , MEETING
    , MEETING_TIME_SLOT
    , MEETING_USERS
    , MEETING_WORKSPACE
    , MEETING_LOCATION
    , MEETING_START
    , DELETING
    , DELETING_CONFIRMATION
    ) = range(15)

end_command = "/done"
