(ACTION, LIST_OF_MEETINGS, LOCATION, LOCATION_NAME, LOCATION_ADDED, WORKSPACE,
WORKSPACE_ADDED, MEETING, MEETING_TIME_SLOT, MEETING_USERS, MEETING_WORKSPACE,
MEETING_LOCATION, MEETING_START, MEETING_NAME, DELETING, DELETING_CONFIRMATION,
MEETING_END
 ) = range(17)

end_command = "/done"
