(ACTION, LIST_OF_MEETINGS, LOCATION, LOCATION_NAME, LOCATION_ADDED, WORKSPACE, MEETING, MEETING_TIME_SLOT, MEETING_USERS, MEETING_WORKSPACE, MEETING_LOCATION, MEETING_START, MEETING_NAME, MEETING_END, DELETING, DELETING_CONFIRMATION
 ) = range(16)

end_command = "/done"
